#%RAML 1.0 Library

types:
  UserRequest:
    type: object
    properties:
      "First Name":
        type: string
        example: "Matthew"
        required: true
      "Last Name":
        type: string
        example: "Tabios"
        required: true
    example:
      "First Name": "Matthew"
      "Last Name": "Tabios"
  
  SuccessResponse:
    type: object
    properties:
      code:
        type: integer
        example: 200
      response:
        type: string
        example: "Successfull Create"
    example:
      code: 200
      response: "Successfull Create"
  
  ProductRequest:
    type: object
    properties:
      amount:
        type: number
        example: 500
        required: true
      quantity:
        type: number
        example: 5
        required: true
    example:
      amount: 500
      quantity: 5
  
  ProductResponse:
    type: object
    properties:
      value:
        type: number
        example: 2500
    example:
      value: 2500
  
  ComplexProductRequest:
    type: object
    properties:
      amount:
        type: number
        example: 200
        required: true
      quantity:
        type: number
        example: 2
        required: true
      type:
        type: string
        example: "toy"
        required: true
      material:
        type: string
        example: "plastic"
        required: true
    example:
      amount: 200
      quantity: 2
      type: "toy"
      material: "plastic"
  
  ComplexProductResponse:
    type: object
    properties:
      value:
        type: number
        example: 400
      kind:
        type: string
        example: "plastic toy"
      "For Kids":
        type: boolean
        example: true
    example:
      value: 400
      kind: "plastic toy"
      "For Kids": true
