#%RAML 1.0 Library

types:
  UserRequest:
    type: object
    properties:
      "First Name":
        type: string
        example: "Matthew"
        required: true
      "Last Name":
        type: string
        example: "Tabios"
        required: true
    example:
      "First Name": "Matthew"
      "Last Name": "Tabios"
  
  SuccessResponse:
    type: object
    properties:
      code:
        type: integer
        example: 200
      response:
        type: string
        example: "Successfull Create"
    example:
      code: 200
      response: "Successfull Create"
  
  ProductRequest:
    type: object
    properties:
      amount:
        type: number
        example: 500
        required: true
      quantity:
        type: number
        example: 5
        required: true
    example:
      amount: 500
      quantity: 5
  
  ProductResponse:
    type: object
    properties:
      value:
        type: number
        example: 2500
    example:
      value: 2500
