#%RAML 1.0
title: Test System API
version: v1
baseUri: /test-system-api

uses:
  DataTypes: libraries/data-types.raml
  Traits: libraries/traits.raml

/kyc:
  post:
    displayName: System KYC Data Access
    description: System API for direct KYC data access and basic validation
    is: [Traits.jsonBody, Traits.standardResponse, Traits.systemHeaders]
    body:
      application/json:
        type: DataTypes.KycRequest
    responses:
      200:
        body:
          application/json:
            type: DataTypes.KycResponse
