#%RAML 1.0
title: Test Experience API
version: v1
baseUri: /test-experience-api

uses:
  DataTypes: libraries/data-types.raml
  Traits: libraries/traits.raml

/kyc:
  post:
    displayName: Process KYC Request
    description: Process Know Your Customer (KYC) request for account verification
    is: [Traits.jsonBody, Traits.standardResponse, Traits.securityHeaders, Traits.rateLimited]
    body:
      application/json:
        type: DataTypes.KycRequest
    responses:
      200:
        body:
          application/json:
            type: DataTypes.KycResponse
